/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.demo.imc;

import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_name_label = new javax.swing.JLabel();
        estatura_name_label = new javax.swing.JLabel();
        peso_name_label = new javax.swing.JLabel();
        estatura_field = new javax.swing.JTextField();
        peso_field = new javax.swing.JTextField();
        calcular_button = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title_name_label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title_name_label.setText("Calculadora de IMC");

        estatura_name_label.setText("Estatura:");

        peso_name_label.setText("Peso:");

        estatura_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estatura_fieldActionPerformed(evt);
            }
        });

        peso_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_fieldActionPerformed(evt);
            }
        });

        calcular_button.setBackground(new java.awt.Color(51, 102, 255));
        calcular_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        calcular_button.setLabel("Calcular IMC");
        calcular_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(title_name_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calcular_button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(estatura_name_label)
                                .addGap(18, 18, 18)
                                .addComponent(estatura_field, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(peso_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peso_field, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estatura_name_label)
                    .addComponent(peso_name_label)
                    .addComponent(estatura_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(calcular_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        title_name_label.getAccessibleContext().setAccessibleName("título");
        title_name_label.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estatura_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estatura_fieldActionPerformed
        
        
    }//GEN-LAST:event_estatura_fieldActionPerformed

    private void peso_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_fieldActionPerformed
        
        
    }//GEN-LAST:event_peso_fieldActionPerformed

    private void calcular_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_buttonActionPerformed
        String estatura = this.estatura_field.getText();
        String peso = this.peso_field.getText();
        Float estatura_float = Float.valueOf(estatura);
        Float peso_float = Float.valueOf(peso);
        Float imc = peso_float/estatura_float;
        if(imc < 18.5){
            JOptionPane.showMessageDialog(rootPane, "Peso inferior al normal");
        }else if(imc >= 18.5 && imc <= 24.9){
            JOptionPane.showMessageDialog(rootPane, "Normal");
        }else if(imc >= 25.0 && imc <= 29.9){
            JOptionPane.showMessageDialog(rootPane, "Peso superior al normal");
        }else if(imc > 30.0){
            JOptionPane.showMessageDialog(rootPane, "Obesidad");
        }else {
            JOptionPane.showMessageDialog(rootPane, "Datos erróneos");
        }
           
    }//GEN-LAST:event_calcular_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button calcular_button;
    private javax.swing.JTextField estatura_field;
    private javax.swing.JLabel estatura_name_label;
    private javax.swing.JTextField peso_field;
    private javax.swing.JLabel peso_name_label;
    private javax.swing.JLabel title_name_label;
    // End of variables declaration//GEN-END:variables
}
